# -*- coding: utf-8 -*-
"""ROI calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UI74BriyjJGosnq7x3CQaf24bkH1tX5B
"""

from prettytable import PrettyTable
from termcolor import colored

# Entrée des données
salaire_brut_annuel = float(input("Entrez le salaire brut annuel du recruteur (en €) : "))
temps_calibrage_sourcing = float(input("Entrez le temps passé par semaine sur le calibrage du sourcing, le mapping du secteur, la recherche de profil sur LinkedIn ou autre plateforme de sourcing, sur la révision des profils identifiés (en heures) : "))
temps_recherche_contact = float(input("Entrez le temps passé par semaine sur la recherche d'information de contact (en heures) : "))
temps_contact_direct = float(input("Entrez le temps passé par semaine à contacter les candidats par approche directe et à les relancer (en heures) : "))
temps_suivi_sourcing = float(input("Entrez le temps passé par semaine à suivre le sourcing, répondre aux candidats et organiser les premiers entretiens (en heures) : "))
temps_suivi_manager = float(input("Entrez le temps passé par semaine sur le suivi avec le hiring manager et l'ajustement du sourcing (en heures) : "))
cout_outils_sourcing = float(input("Entrez le coût mensuel des outils de sourcing utilisés, plateformes, ressources externes (RPO, agences de recrutement, etc.) (en €) : "))

# Calculs
charges_sociales = 0.40
cout_horaire = (salaire_brut_annuel * (1 + charges_sociales)) / (52 * 40)
cout_total_sourcing = (temps_calibrage_sourcing + temps_recherche_contact + temps_contact_direct + temps_suivi_sourcing + temps_suivi_manager) * cout_horaire * 4
cout_total_mensuel = cout_total_sourcing + cout_outils_sourcing

# Tableau avec PrettyTable
table = PrettyTable()
table.field_names = [colored("Description", "blue"), colored("Montant (€)", "blue")]
table.add_row([colored("Coût horaire moyen du recruteur (charges incluses)", "blue"), colored(f"{cout_horaire:.2f}", "cyan")])
table.add_row([colored("Coût total par mois pour le sourcing de candidats", "blue"), colored(f"{cout_total_sourcing:.2f}", "cyan")])
table.add_row([colored("Coût total mensuel incluant les outils de sourcing", "blue"), colored(f"{cout_total_mensuel:.2f}", "cyan")])

print(table)